name: WEB - Docker Publish

env:
  REGISTRY: artifacts.developer.gov.bc.ca
  REPOSITORY_NAME: plat-gen-docker-local/just-ask-web

on: 
  workflow_dispatch:
  push:
    paths: 
      - 'web/**'
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 #v5.7.0
        with:
          images: ${{env.REGISTRY}}/${{ env.REPOSITORY_NAME }}
          # Always generate latest tag (https://github.com/docker/metadata-action#latest-tag)
          flavor: latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Login to Artifactory
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
      - # Support for multiplatform build. Using for dev debugging
        name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 #v3.6.0
              
      - # Support for multiplatform build. Using for dev debugging
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0
        
      - name: Build container
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 #v6.16.0
        with:
          context: "{{defaultContext}}:web"
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max
