name: WEB - Docker Publish

env:
  REGISTRY: artifacts.developer.gov.bc.ca
  REPOSITORY_NAME: plat-gen-docker-local/just-ask-web

on: 
  workflow_dispatch:
  push:
    paths: 
      - 'web/**'
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.REGISTRY}}/${{ env.REPOSITORY_NAME }}
          # Always generate latest tag (https://github.com/docker/metadata-action#latest-tag)
          flavor: latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
      - # Support for multiplatform build. Using for dev debugging
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
              
      - # Support for multiplatform build. Using for dev debugging
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:web"
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max
