name: Aqua Trivy Vulnerability Scanner
on:
 #branches:
 # -main
 # -releases/XX
 #branches-ignore:
 # -main
 # -releases/XX
 #tags-ignore:
 # -v1.

  push: #Any push will trigger this action
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '*.md'
  # schedule:
    # Layout of cron schedule.  'minute hour day(month) month day(week)'
    # Schedule option to review code at rest for possible net-new threats/CVE's
    # List of Cron Schedule Examples can be found at https://crontab.guru/examples.html
    # Top of Every Hour ie: 17:00:00. '0 * * * *'
    # Midnight Daily ie: 00:00:00. '0 0 * * *'
    # 12AM UTC --> 8PM EST. '0 0 * * *'
    # Midnight Friday. '0 0 * * FRI'
    # Once a week at midnight Sunday. '0 0 * * 0'
    # First day of the month at midnight. '0 0 1 * *'
    # Every Quarter. '0 0 1 */3 *'
    # Every 6 months. '0 0 1 */6 *'
    # Every Year. '0 0 1 1 *' 
    # - cron: '0 0 * * *'
jobs:
  web:
    name: Aqua Trivy Vulnerability Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        #Update the docker image below
        run: |
          docker build -t just-ask-web web
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
        #Update the image reference within the above docker repository
          image-ref: 'just-ask-web'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
  api:
    name: Aqua Trivy Vulnerability Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        #Update the docker image below
        run: |
          docker build -t just-ask-api api
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
        #Update the image reference within the above docker repository
          image-ref: 'just-ask-api'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'